sudo: false
language: node_js
node_js:
  - 'stable'
env:
  matrix:
    - BROWSER=Chrome PLATFORM='Windows 8' VERSION=38
    - BROWSER=Chrome PLATFORM='Windows 7' VERSION=37
    - BROWSER=Firefox PLATFORM='Linux' VERSION=30
    - BROWSER=Firefox PLATFORM='OS X 10.9' VERSION=29
  global:
    - SAUCE_USERNAME=compose-ci
    - SAUCE_ACCESS_KEY=60671366-2ef6-4ed3-8de0-cc95f065a41f
addons:
  sauce_connect: true
