language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: AAbayYPPJVsIaMiF5tmiFQWoxUKdXq74MHsJzdbFiMbUB0vdgnX9rBftatL+dftdBw36iIk8FhHeteV0rM1dH2wDyLviDsBdRKxkZ2xj2EcBQJRSji/Y0ZIh6klTRN7A1bektALrsVNDAK759N8RPM000HHfx/Ufw+ts+zxXxXE=
  - secure: Qlt3nMSpOMuFCYD9D5gbnQHDbRQnUNmplr8oA4Y24c9plGVPYQ5s5DDUmy9x2/zMpsOniYZB13qtToVl6y93HRwKi6xDQ6B+88bRZ3kKW23NWJIY//+XVh4S0swegQwqXR2fdFGAELx34dwrqC1XRRM4zGI4JnyOtbaz3AAdda0=
addons:
  sauce_connect: true
install:
  - npm install -d --quiet
before_script: npm run server
after_script: killall node
